<div id="mission" class="gred-box">
    <div class="gred-header">Our Vision</div>
    <div class="gred-body">
        <p>To be the caring, compassionate healer in the region for diverse 
            communities.</p>
    </div>
</div>
<div id="vission" class="gred-box">
    <div class="gred-header">Our Mission</div>
    <div class="gred-body">
        <p>To heal, to offer comprehensive services in an environmentally 
            friendly way; where we serve patients and one another while meeting 
            challenging complex medical needs; where quality and safety are 
            inevitable.</p>
    </div>
</div>
<div id="img-galery" class="img-gal">

</div>
