<script type="text/javascript">
    $(document).ready(function(){
        $('#add-room').button();       
    });
</script>

<? if (!$this->room) { ?>
    <?php if ($this->isAllowed('room', 'add')) { ?>
        <span id="add-room" class="floatright marb25">
            <a href="<?php echo $this->url(
                        array(
                            'controller' => 'room',
                            'action' => 'add'
                        ), 'default', true
        );
        ?>">Add Room</a>
        </span>
    <?php } ?>
<?php } ?>

<div class="clear"></div>

<?php $this->displayMessage($this->message); ?>

<?php if ($this->room) { ?>
    <div id="add-form">
        <?php echo $this->form; ?>
    </div>
<?php } ?>