<script type="text/javascript">
    var baseUrl = "<?php echo $this->baseUrl(); ?>";

    $(document).ready(function(){
        $("#add-checking").button();
        
        $('.delete').click(function () {
            $('.mes_row').remove();
            $('#mes').empty();

            var thisrow = $(this).parents('tr');
            var id = thisrow.attr('id');

            var mes_row = '<tr class="mes_row"><td colspan="5">'
                + 'Are you sure you want to delete this checking? &nbsp;'
                + '<input class="yes" value="Yes" type="button" /> &nbsp'
                + '<input class="no" value="No" type="button" />'
                + '</td></tr>';
            $(this).parents('tr').after(mes_row);
            
            $('.yes').click(function () {

                var path = baseUrl+'/checking/delete/';

                $.post(path, {id:id}, function(data) {
                    $('.mes_row').remove();	
                    if (data.search( "DELETECODE1" )!=-1) {    
                                            
                        thisrow.hide(2500);
                        var success = '<div class="success">'
                            + '<ul><li>Checking delete successfully</li></ul></div>';
                        $('#mes').html(success);                      
                        if ($('.data-table tbody tr').length == 1) {
                            $('.data-table').hide(2500);
                            var empty = '<div class="mart50 jnotice ui-state-highlight ui-corner-all">'
                                + '<span class="ui-icon ui-icon-info message"></span>Checkups not found' 
                                + '</div>';
                            $('#add-checking').after(empty)
                        }
                        
                    }                   
                    else {
                        var errors = '<div class="errors">'
                            + '<ul><li>Checkup delete unsuccessfully</li></ul></div>';
                        $('#mes').html(errors);
                       
                    }                   				
                });
            });

            $('.no').click( function () {
                $('.mes_row').remove();
            });
        });
    });
</script>  

<div id="mes" class="floatleft wid90"></div>
<?php if ($this->isAllowed('checking', 'add')) { ?>
    <span id="add-checking" class="floatright marb25">
        <a href="<?php  echo $this->url(
                            array(
                                'controller' => 'checking',
                                'action' => 'add'
                            ), 'default', true
                );
                ?>">Add  Checkup</a>
    </span>
<?php } ?>

<?php if ($this->checkings) { ?>
    <table class="data-table">
        <thead>
            <tr>
                <th class="alignleft">Name</th>
                <th class="w35"></th>
                <th class="w35"></th>
                <?php if ($this->isAllowed('checking', 'edit')) { ?>
                    <th class="w35"></th>
                <?php } ?>
                <?php if ($this->isAllowed('checking', 'delete')) { ?>
                    <th class="w25"></th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <?php
            $checkingsarray = $this->checkings;
            $trows = '';

            foreach ($checkingsarray as $checking) {
                $trows .= '<tr id="' . $checking['id'] . '">';
                $trows .= '<td >' . $checking['name'] . '</td>';               
                $trows .= '<td class="aligncenter">'
                        . '<a class="checking-view" title="View Checkup Details" href="'
                        . $this->url(
                                array(
                            'controller' => 'checking',
                            'action' => 'view',
                            'id' => $checking['id']
                                ), 'default', true
                        ) . '"></a></td>';

                $trows .= '<td class="aligncenter">'
                        . '<a class="changeling" title="Book Checkup" href="'
                        . $this->url(
                                array(
                            'controller' => 'checking',
                            'action' => 'book',
                            'id' => $checking['id']
                                ), 'default', true
                        ) . '"/></td>';
                
                if ($this->isAllowed('checking', 'edit')) {
                    $trows .= '<td class="aligncenter">'
                            . '<a class="edit" title="Edit Checkup Details" href="'
                            . $this->url(
                                    array(
                                'controller' => 'checking',
                                'action' => 'edit',
                                'id' => $checking['id']
                                    ), 'default', true
                            ) . '"></a></td>';
                }
                
                if ($this->isAllowed('checking', 'delete')) {
                    $trows .= '<td class="aligncenter">'
                            . '<a class="delete" title="Delete Checkup" href="javascript:void(0);"/></td>';
                }
                
                $trows .= '</tr>';
            }

            echo $trows;
            ?>

        </tbody>
    </table>


<?php } else { ?>
    <div class="mart50 jnotice ui-state-highlight ui-corner-all">
        <span class="ui-icon ui-icon-info message"></span>Checkup not found
    </div>
<?php } ?>