<table id="page">
    <tbody>
        <tr>
            <td>
                <div class="content border2">
                    <div class="intellectual">                       
                        <div class="clear"></div>                        
                        <div class="otherbox box_format_1-21 font_format_1">                         
                            <table class="font_format_1">
                                <tbody><tr>
                                        <td class="table_format_5-1">
                                            <span class="font_format_8">Address:</span><br><br>
                                            <span class="font_format_2">Ispirithalaya<br> No 195/7,<br>  Pansala Para,<br> Maharagama<br></span>
                                        </td>
                                        <td class="table_format_5-1">
                                            <span class="font_format_8">Contact No : </span><br><br>
                                            <span class="font_format_2">Tel1:   0372288158 <br> Tel2:   0375689268  </span> 

                                        </td>
                                        <td class="table_format_5-1">
                                            <span class="font_format_8">Fax : </span>
                                            <span class="font_format_2">0112288159</span>   <br><br>
                                            <span class="font_format_8">Email : </span>
                                            <span class="font_format_2">admin@ispirithalaya.lk</span> 
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                       </div>
                    </div>
                </div>              
            </td>
        </tr>       
    </tbody>
</table>
